---
- name: Test Ansible connectivity
  ansible.builtin.import_playbook: ansible-connectivity.yml

- name: Deploy a web application
  hosts: database01
  roles:
    - os-config
    - database
    - web
